[project]
name = 'Vote-Sphere'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Vote-Sphere]
path = 'contracts/Vote-Sphere.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = []
